version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa1234
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data: